---

KVM_GROUP_NAME: kvm

# Primary user account you use on the server
NON_ROOT_SUDO_USER: relias

# Directory where ISO images will be stored.
ISO_STORAGE_DIRECTORY: /var/lib/libvirt/images/ISO

# Static IP configuration
NETWORK_GATEWAY: 192.168.1.1
NETWORK_NAMESERVERS: '8.8.8.8,8.8.4.4'
